services:

  app:
    build: .
    env_file:
      - .env
    working_dir: /app
    command: bash -c "$DOCKER_COMMAND"
    ports:
      - 0.0.0.0:${DOCKER_PORT}:8080
    volumes:
      - .:/app/

  worker:
    build: .
    env_file:
      - .env
    working_dir: /app
    command: python worker.py
    volumes:
      - .:/app/
    restart: unless-stopped
